apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ui
  labels:
    app: react-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-ui
  template:
    metadata:
      labels:
        app: react-ui
    spec:
      containers:
      - name: react-ui
        image: "docker.pkg.github.com/simonjamesrowe/react-ui/react-ui:latest"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-ui
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: react-ui
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - www.simonjamesrowe.com
    secretName: wildcart-cert
  rules:
  - host: www.simonjamesrowe.com
    http:
      paths:
      - path: /
        backend:
          serviceName: react-ui
          servicePort: 80
