apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config
data:
  config.js: >
    window.API_URL="{{ .Values.apiUrl }}";
    window.GA_TRACKING_TOKEN="{{ .Values.gaTrackingToken }}";
    window.HOT_JAR_TRACKING_TOKEN="{{ .Values.hotJarTrackingToken}}";